apiVersion: v1
kind: Pod
metadata:
  name: pod-python
  labels:
    name: python
spec:
  containers:
    - name: helloworld-pyth
      image: 13455/python:1.0
      ports:
        - containerPort: 5003
